services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    container_name: nextjs-app
    volumes:
      - .:/app
      - /app/node_modules   # prevent node_modules from being overwritten
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    networks:
      - heapdog-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app-prod
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - NODE_ENV=production
    networks:
      - heapdog-network


networks:
  heapdog-network:
    external: true
